#cloud-config
write_files:
  - path: /opt/etc/consul/common.json
    owner: "100:1000"
    permissions: "0600"
    content: |
      {
          "datacenter" : "${CONSUL_DATACENTER}",
          "domain"     : "${CONSUL_DOMAIN}.",
          "retry_join" : [ "provider=aws tag_key=${CONSUL_DISCOVERY_LAN_KEY} tag_value=${CONSUL_DISCOVERY_LAN_VALUE}" ]
      }
  - path: /etc/docker/daemon.json
    owner: "root:root"
    permissions: "0600"
    content: |
      {
          "bip" : "${DOCKER_BRIDGE_CIDR}"
      }

rancher:
  docker:
    engine: docker-${DOCKER_VERSION}
  environment:
    CONSUL_BRIDGE_CIDR: ${CONSUL_BRIDGE_CIDR}
    CONSUL_BRIDGE_HOST: ${CONSUL_BRIDGE_HOST}
    CONSUL_BRIDGE_NAME: ${CONSUL_BRIDGE_NAME}
    CONSUL_DATACENTER: ${CONSUL_DATACENTER}
    CONSUL_DOMAIN: ${CONSUL_DOMAIN}
    CONSUL_DISCOVERY_LAN_KEY: ${CONSUL_DISCOVERY_LAN_KEY}
    CONSUL_DISCOVERY_LAN_VALUE: ${CONSUL_DISCOVERY_LAN_VALUE}
    CONSUL_VERSION: ${CONSUL_VERSION}
  network:
    interfaces:
      ${CONSUL_BRIDGE_NAME}:
        address: ${CONSUL_BRIDGE_CIDR}
        bridge: true
        dhcp: false
  services:
    consul:
      environment:
        CONSUL_BIND_INTERFACE: eth0
        CONSUL_LOCAL_CONFIG: '${CONSUL_LOCAL_CONFIG}'
      command: agent -client 0.0.0.0
      container_name: ${CONSUL_BRIDGE_HOST}
      image: consul:${CONSUL_VERSION}
      labels:
        io.rancher.os.after: console
        io.rancher.os.scope: system
      net: host
      pid: host
      restart: unless-stopped
      volumes_from:
       - all-volumes
      volumes:
        - "/opt/etc/consul:/consul/config:rw"
        - "/var/lib/consul:/consul/data:rw"
        - "/var/run:/var/run:rw"
